-- 3.6: squad bingo. A card a week, the same for every squad: the server
-- draws it once from the pool (bingo_pool, the admin edits it) and keeps it
-- (bingo_cards), so every board plays the same card and an edit shows from
-- the next week's draw. Each member's row carries `play`: facts about their
-- own week (which squares they passed, the days they studied, cheers sent),
-- the same in every squad they're in; boards add the rows up.
ALTER TABLE members ADD COLUMN play TEXT;
CREATE TABLE bingo_pool (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,            -- square | middle
  json TEXT NOT NULL,            -- the entry: its words, rule type and numbers
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at INTEGER NOT NULL
);
CREATE TABLE bingo_cards (
  wk TEXT PRIMARY KEY,           -- 2026-W40
  json TEXT NOT NULL,            -- the card as drawn: 8 squares and the middle
  stats TEXT,                    -- the daily cron's counts: how many stamped each square
  created_at INTEGER NOT NULL
);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('emon', 'square', '{"fam":"early","diff":"e","icon":"☀️","title":"Monday morning","rule":"A review before noon on Monday","detail":"Any review before 12:00 on Monday.","type":"window","params":{"from":0,"to":12,"days":1,"dow":[0]},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('e8x2', 'square', '{"fam":"early","diff":"m","icon":"🌅","title":"Early bird","rule":"Before 8am, on 2 days","detail":"A review before 8:00 on two days this week, by your computer''s clock.","type":"window","params":{"from":0,"to":8,"days":2},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('ewknd', 'square', '{"fam":"early","diff":"h","icon":"☕","title":"Weekend mornings","rule":"Before 9am, Saturday and Sunday","detail":"A review before 9:00 on both Saturday and Sunday.","type":"window","params":{"from":0,"to":9,"days":2,"dow":[5,6]},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('s2', 'square', '{"fam":"spread","diff":"e","icon":"🔁","title":"Two sittings","rule":"2 sessions in a day, an hour apart","detail":"Two sessions in one day, the second starting an hour or more after the first ended.","type":"sittings","params":{"n":2,"gap":60},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('sampm', 'square', '{"fam":"spread","diff":"m","icon":"🌗","title":"Morning and evening","rule":"Before noon and after 6, same day","detail":"A review before 12:00 and another after 18:00 on the same day.","type":"parts","params":{"parts":[[0,12],[18,24]],"days":1},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('s3', 'square', '{"fam":"spread","diff":"h","icon":"🌈","title":"Morning, noon, night","rule":"Before noon, 12–6 and after 6, one day","detail":"Reviews in all three parts of one day: before 12:00, 12:00–17:59 and 18:00 on.","type":"parts","params":{"parts":[[0,12],[12,18],[18,24]],"days":1},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('f20', 'square', '{"fam":"focus","diff":"e","icon":"⏱️","title":"Twenty minutes","rule":"20 minutes, no break","detail":"20 minutes of reviews without a gap of 5 minutes or more.","type":"focus","params":{"minutes":20,"gap":5},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('f40', 'square', '{"fam":"focus","diff":"m","icon":"🎧","title":"Forty minutes","rule":"40 minutes, no break","detail":"40 minutes of reviews without a gap of 5 minutes or more.","type":"focus","params":{"minutes":40,"gap":5},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('f60', 'square', '{"fam":"focus","diff":"h","icon":"🧘","title":"The full hour","rule":"An hour, no break","detail":"60 minutes of reviews without a gap of 5 minutes or more.","type":"focus","params":{"minutes":60,"gap":5},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('vyest', 'square', '{"fam":"volume","diff":"e","icon":"📈","title":"Beat yesterday","rule":"More reviews than the day before","detail":"Any day with more reviews than the day before it.","type":"beat","params":{"run":1},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('v15', 'square', '{"fam":"volume","diff":"m","icon":"💪","title":"Big day","rule":"1.5× your usual day","detail":"A day with half as many reviews again as your usual: your average over the last 30 days you studied.","type":"rel","params":{"x":1.5},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('vbest', 'square', '{"fam":"volume","diff":"h","icon":"🚀","title":"Best in a month","rule":"Your biggest day in 30","detail":"More reviews in one day than on any of your last 30 days.","type":"best","params":{"days":30},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('n3', 'square', '{"fam":"fresh","diff":"e","icon":"🌱","title":"Something new","rule":"New cards on 3 days","detail":"At least one new card on three days this week.","type":"newdays","params":{"days":3},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('ndone', 'square', '{"fam":"fresh","diff":"m","icon":"🌿","title":"New done","rule":"All your new cards, 3 days","detail":"Three days on which you finish the new cards your decks give you.","type":"newdone","params":{"days":3},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('n6', 'square', '{"fam":"fresh","diff":"h","icon":"🌳","title":"New every day","rule":"New cards on 6 days","detail":"At least one new card on six days this week.","type":"newdays","params":{"days":6},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('o5', 'square', '{"fam":"often","diff":"e","icon":"✋","title":"High five","rule":"Study on 5 days","detail":"At least one review on five days this week.","type":"days","params":{"days":5},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('owk', 'square', '{"fam":"often","diff":"m","icon":"🧦","title":"Weekend","rule":"Saturday and Sunday","detail":"At least one review on both Saturday and Sunday.","type":"days","params":{"days":2,"dow":[5,6]},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('o7', 'square', '{"fam":"often","diff":"h","icon":"🗓️","title":"7 of 7","rule":"Every day this week","detail":"At least one review on each day, Monday to Sunday.","type":"days","params":{"days":7},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('z1', 'square', '{"fam":"clean","diff":"e","icon":"🧹","title":"Due zero","rule":"A day with nothing left due","detail":"A day that ends with nothing due in every deck you studied that day.","type":"zero","params":{"days":1},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('z3', 'square', '{"fam":"clean","diff":"m","icon":"🧼","title":"Clean three","rule":"Due zero on 3 days","detail":"Three days this week that end with nothing due in the decks you studied.","type":"zero","params":{"days":3},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('z5', 'square', '{"fam":"clean","diff":"h","icon":"🫧","title":"Clean week","rule":"Due zero on 5 days","detail":"Five days this week that end with nothing due in the decks you studied.","type":"zero","params":{"days":5},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('wlunch', 'square', '{"fam":"wild","diff":"e","icon":"🥪","title":"Lunch break","rule":"A review between 12 and 1","detail":"Any review between 12:00 and 12:59.","type":"window","params":{"from":12,"to":13,"days":1},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('w1111', 'square', '{"fam":"wild","diff":"m","icon":"✨","title":"11:11","rule":"A review at 11:11","detail":"Any review at 11:11, morning or night. Make a wish.","type":"minute","params":{"hm":["11:11","23:11"]},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('wowl', 'square', '{"fam":"wild","diff":"m","icon":"🌙","title":"Night owl","rule":"After 10pm, on 2 nights","detail":"Reviews after 22:00 on two nights, before Anki''s next day starts.","type":"window","params":{"from":22,"to":24,"days":2},"team":true}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('wpi', 'square', '{"fam":"wild","diff":"m","icon":"🥧","title":"π o''clock","rule":"A review at 3:14","detail":"Any review at 3:14, afternoon or night.","type":"minute","params":{"hm":["15:14","03:14"]},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('wsame', 'square', '{"fam":"wild","diff":"h","icon":"🕰️","title":"Same time","rule":"Start in the same hour, 4 days running","detail":"Your first review of the day in the same hour, four days in a row.","type":"samehour","params":{"run":4},"team":false}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('allhands', 'middle', '{"group":"study","icon":"🙌","name":"All hands","rule":"Everyone, one day","detail":"A day on which every one of you studies.","type":"day","params":{"key":"d"},"goal":"all","unit":"studied"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('roll', 'middle', '{"group":"study","icon":"📋","name":"Roll call","rule":"Everyone studies once","detail":"Every one of you studies at least once this week.","type":"people","params":{"key":"d"},"goal":"all","unit":"studied"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('sunday', 'middle', '{"group":"study","icon":"☀️","name":"Sunday club","rule":"Half of you on Sunday","detail":"Half of you or more study on Sunday.","type":"day","params":{"key":"d","day":6},"goal":"half","unit":"on Sunday"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('dawn', 'middle', '{"group":"study","icon":"🌅","name":"Dawn patrol","rule":"3 of you before 8am, same day","detail":"Three of you with a review before 8:00 on the same day.","type":"day","params":{"key":"e8"},"goal":3,"unit":"early"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('clean', 'middle', '{"group":"study","icon":"🧹","name":"Clean slate","rule":"4 of you hit due zero","detail":"Four of you end a day with nothing due.","type":"people","params":{"key":"z"},"goal":4,"unit":"clean"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('emoji', 'middle', '{"group":"crew","icon":"🎨","name":"Picture day","rule":"Everyone has an emoji","detail":"Every one of you picks an emoji (You › Emoji).","type":"emoji","params":{},"goal":"all","unit":"have one"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('hi', 'middle', '{"group":"crew","icon":"👋","name":"Say hi","rule":"5 cheers between you","detail":"Five cheers sent between any of you this week.","type":"sum","params":{"key":"ch"},"goal":5,"unit":"sent"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('room', 'middle', '{"group":"crew","icon":"🏕️","name":"Campfire","rule":"3 of you in a study room","detail":"Three of you join a study room this week.","type":"people","params":{"key":"rm"},"goal":3,"unit":"joined"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('buddy', 'middle', '{"group":"crew","icon":"🟢","name":"I''m studying","rule":"3 of you turn it on","detail":"Three of you turn on I''m studying this week.","type":"people","params":{"key":"lv"},"goal":3,"unit":"on"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('ask', 'middle', '{"group":"crew","icon":"🙋","name":"Ask away","rule":"Someone asks about a card","detail":"Someone asks their crew about a card this week.","type":"sum","params":{"key":"aq"},"goal":1,"unit":"asked"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('tip', 'middle', '{"group":"crew","icon":"💡","name":"Good tips","rule":"3 tips between you","detail":"Three tips written on cards between you this week.","type":"sum","params":{"key":"tp"},"goal":3,"unit":"written"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('deck', 'middle', '{"group":"crew","icon":"📚","name":"Show and tell","rule":"3 of you share a deck","detail":"Three of you share at least one deck.","type":"people","params":{"key":"dk"},"goal":3,"unit":"sharing"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('status', 'middle', '{"group":"crew","icon":"💬","name":"Status update","rule":"3 of you set a status","detail":"Three of you set a status line this week.","type":"people","params":{"key":"st"},"goal":3,"unit":"set"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('friend', 'middle', '{"group":"crew","icon":"🤝","name":"Bring a friend","rule":"Someone new joins","detail":"Someone new joins the squad this week.","type":"joined","params":{},"goal":1,"unit":"joined"}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('coffee', 'middle', '{"group":"free","icon":"☕","name":"Coffee week","rule":"Free. It''s on the house.","detail":"Every sixth week the middle is free.","type":"free","params":{},"goal":1,"unit":""}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('newyear', 'middle', '{"group":"season","icon":"🎆","name":"First week back","rule":"Everyone studies once","detail":"Every one of you studies at least once in the first week of the year.","type":"people","params":{"key":"d"},"goal":"all","unit":"studied","season":{"from":"12-29","to":"01-04"}}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('spooky', 'middle', '{"group":"season","icon":"🎃","name":"Spooky week","rule":"3 of you after 10pm, same night","detail":"Three of you with a review after 22:00 on the same night.","type":"day","params":{"key":"n10"},"goal":3,"unit":"night owls","season":{"from":"10-26","to":"11-01"}}', 1, 0);
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('spring', 'middle', '{"group":"season","icon":"🌸","name":"Spring clean","rule":"Half of you hit due zero","detail":"Half of you end a day with nothing due.","type":"people","params":{"key":"z"},"goal":"half","unit":"clean","season":{"from":"03-20","to":"03-26"}}', 1, 0);
