-- 3.6.1: squad bingo takes more of the squad. Every square but one is a
-- team square, sized to the squad (easy: half of you, medium: a third,
-- one hard: a quarter; at least 2), so a bigger squad needs more of you;
-- more squares are streaks (`row`: that many days in a row); the middle's
-- goals are shares of the squad too. The cards drawn so far go, so this
-- week's is drawn again under these rules (only the admin has seen it).
-- An entry the admin has edited since keeps the edit (updated_at > 0).

UPDATE bingo_pool SET json = '{"fam":"early","diff":"m","icon":"🌅","title":"Early bird","rule":"Before 8am, 2 days in a row","detail":"A review before 8:00 on two days in a row, by your computer''s clock.","type":"window","params":{"from":0,"to":8,"days":2,"row":true},"team":true}' WHERE id = 'e8x2' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"early","diff":"h","icon":"☕","title":"Weekend mornings","rule":"Before 9am, Saturday and Sunday","detail":"A review before 9:00 on both Saturday and Sunday.","type":"window","params":{"from":0,"to":9,"days":2,"dow":[5,6]},"team":true}' WHERE id = 'ewknd' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"spread","diff":"m","icon":"🌗","title":"Morning and evening","rule":"Before noon and after 6, 2 days in a row","detail":"A review before 12:00 and another after 18:00 on the same day, two days in a row.","type":"parts","params":{"parts":[[0,12],[18,24]],"days":2,"row":true},"team":true}' WHERE id = 'sampm' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"spread","diff":"h","icon":"🌈","title":"Morning, noon, night","rule":"Before noon, 12–6 and after 6, one day","detail":"Reviews in all three parts of one day: before 12:00, 12:00–17:59 and 18:00 on.","type":"parts","params":{"parts":[[0,12],[12,18],[18,24]],"days":1},"team":true}' WHERE id = 's3' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"focus","diff":"h","icon":"🧘","title":"The full hour","rule":"An hour, no break","detail":"60 minutes of reviews without a gap of 5 minutes or more.","type":"focus","params":{"minutes":60,"gap":5},"team":true}' WHERE id = 'f60' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"fresh","diff":"m","icon":"🌿","title":"New done","rule":"All your new cards, 2 days in a row","detail":"Two days in a row on which you finish the new cards your decks give you.","type":"newdone","params":{"days":2,"row":true},"team":true}' WHERE id = 'ndone' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"fresh","diff":"h","icon":"🌳","title":"New every day","rule":"New cards 5 days in a row","detail":"At least one new card on five days in a row.","type":"newdays","params":{"days":5,"row":true},"team":true}' WHERE id = 'n6' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"often","diff":"h","icon":"🗓️","title":"7 of 7","rule":"Every day this week","detail":"At least one review on each day, Monday to Sunday.","type":"days","params":{"days":7},"team":true}' WHERE id = 'o7' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"clean","diff":"m","icon":"🧼","title":"Clean streak","rule":"Due zero, 2 days in a row","detail":"Two days in a row that end with nothing due in the decks you studied.","type":"zero","params":{"days":2,"row":true},"team":true}' WHERE id = 'z3' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"clean","diff":"h","icon":"🫧","title":"Clean week","rule":"Due zero 4 days in a row","detail":"Four days in a row that end with nothing due in the decks you studied.","type":"zero","params":{"days":4,"row":true},"team":true}' WHERE id = 'z5' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"fam":"wild","diff":"h","icon":"🕰️","title":"Same time","rule":"Start in the same hour, 4 days running","detail":"Your first review of the day in the same hour, four days in a row.","type":"samehour","params":{"run":4},"team":true}' WHERE id = 'wsame' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"study","icon":"🌅","name":"Dawn patrol","rule":"A quarter of you before 8am, same day","detail":"A quarter of you (at least 2) with a review before 8:00 on the same day.","type":"day","params":{"key":"e8"},"goal":"quarter","unit":"early"}' WHERE id = 'dawn' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"study","icon":"🧹","name":"Clean slate","rule":"A third of you hit due zero","detail":"A third of you (at least 2) end a day with nothing due.","type":"people","params":{"key":"z"},"goal":"third","unit":"clean"}' WHERE id = 'clean' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"👋","name":"Say hi","rule":"Half of you send a cheer","detail":"Half of you (at least 2) send a cheer this week.","type":"people","params":{"key":"ch"},"goal":"half","unit":"sent one"}' WHERE id = 'hi' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"🏕️","name":"Campfire","rule":"A quarter of you in a study room","detail":"A quarter of you (at least 2) join a study room this week.","type":"people","params":{"key":"rm"},"goal":"quarter","unit":"joined"}' WHERE id = 'room' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"🟢","name":"I''m studying","rule":"A quarter of you turn it on","detail":"A quarter of you (at least 2) turn on I''m studying this week.","type":"people","params":{"key":"lv"},"goal":"quarter","unit":"on"}' WHERE id = 'buddy' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"🙋","name":"Ask away","rule":"A quarter of you ask about a card","detail":"A quarter of you (at least 2) ask the crew about a card this week.","type":"people","params":{"key":"aq"},"goal":"quarter","unit":"asked"}' WHERE id = 'ask' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"💡","name":"Good tips","rule":"A quarter of you write a tip","detail":"A quarter of you (at least 2) write a tip on a card this week.","type":"people","params":{"key":"tp"},"goal":"quarter","unit":"wrote one"}' WHERE id = 'tip' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"📚","name":"Show and tell","rule":"A third of you share a deck","detail":"A third of you (at least 2) share at least one deck.","type":"people","params":{"key":"dk"},"goal":"third","unit":"sharing"}' WHERE id = 'deck' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"crew","icon":"💬","name":"Status update","rule":"A third of you set a status","detail":"A third of you (at least 2) set a status line this week.","type":"people","params":{"key":"st"},"goal":"third","unit":"set"}' WHERE id = 'status' AND updated_at = 0;
UPDATE bingo_pool SET json = '{"group":"season","icon":"🎃","name":"Spooky week","rule":"A quarter of you after 10pm, same night","detail":"A quarter of you (at least 2) with a review after 22:00 on the same night.","type":"day","params":{"key":"n10"},"goal":"quarter","unit":"night owls","season":{"from":"10-26","to":"11-01"}}' WHERE id = 'spooky' AND updated_at = 0;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('e7row', 'square', '{"fam":"early","diff":"h","icon":"🐓","title":"Up with the sun","rule":"Before 7am, 3 days in a row","detail":"A review before 7:00 on three days in a row.","type":"window","params":{"from":0,"to":7,"days":3,"row":true},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('f20x3', 'square', '{"fam":"focus","diff":"m","icon":"⏳","title":"Twenty a day","rule":"20 minutes, no break, 3 days in a row","detail":"A 20-minute stretch without a 5-minute gap, three days in a row.","type":"focus","params":{"minutes":20,"gap":5,"days":3,"row":true},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('vup3', 'square', '{"fam":"volume","diff":"h","icon":"📈","title":"Up, up, up","rule":"More than the day before, 3 days running","detail":"Three days in a row, each with more reviews than the day before.","type":"beat","params":{"run":3},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('n3row', 'square', '{"fam":"fresh","diff":"m","icon":"🌱","title":"New streak","rule":"New cards 3 days in a row","detail":"At least one new card on three days in a row.","type":"newdays","params":{"days":3,"row":true},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('o4row', 'square', '{"fam":"often","diff":"m","icon":"🔗","title":"Four in a row","rule":"Study 4 days in a row","detail":"At least one review on four days in a row.","type":"days","params":{"days":4,"row":true},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
INSERT INTO bingo_pool (id, kind, json, enabled, updated_at) VALUES ('wlunch3', 'square', '{"fam":"wild","diff":"m","icon":"🥪","title":"Lunch club","rule":"A review 12–1, 3 days in a row","detail":"A review between 12:00 and 12:59 on three days in a row.","type":"window","params":{"from":12,"to":13,"days":3,"row":true},"team":true}', 1, 0) ON CONFLICT(id) DO NOTHING;
DELETE FROM bingo_cards;
