#!/usr/bin/env python3
"""Builds site/src/og_assets.ts: what the site Worker needs to draw a plan
link's preview picture (3.5, A2) without a font engine. Glyphs of Inter
(SIL Open Font License 1.1, rsms.me/inter) at the picture's three sizes,
drawn once here as 4-bit alpha, and the one-line logo (docs/logo, as drawn:
never redrawn) as RGBA. Needs Pillow; fetches Inter from Google Fonts.

    python3 tools/og_assets.py            # writes site/src/og_assets.ts
"""

import base64
import json
import os
import sys
import tempfile
import urllib.request
import zlib

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "site", "src", "og_assets.ts")
LOGO = os.path.join(ROOT, "docs", "logo", "png", "due-crew-logo-line-910.png")
LOGO_H = 44  # px in the 1200x630 picture

INTER = {
    "regular": "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZg.ttf",
    "bold": "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZg.ttf",
}
# name: (weight, px). The title, the lines under it, the code.
FACES = {"title": ("bold", 62), "text": ("regular", 30), "strong": ("bold", 30)}
# ASCII, Latin-1, Latin Extended-A, and the punctuation plan names use
CHARS = ([chr(c) for c in range(32, 127)] + [chr(c) for c in range(160, 384)]
         + list("–—‘’“”…·•€→≤≥×"))


def fetch(url: str, into: str) -> str:
    path = os.path.join(into, url.rsplit("/", 1)[-1])
    if not os.path.exists(path):
        with urllib.request.urlopen(url, timeout=60) as r, open(path, "wb") as f:
            f.write(r.read())
    return path


def face(path: str, px: int):
    """[metrics per glyph], bytes: each glyph's alpha, two pixels a byte."""
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    glyphs, blob = [], bytearray()
    for ch in dict.fromkeys(CHARS):
        if font.getmask(ch).size == (0, 0) and ch != " ":
            continue
        adv = font.getlength(ch)
        l, t, r, b = font.getbbox(ch, anchor="ls")  # relative to the pen on the baseline
        w, h = max(0, r - l), max(0, b - t)
        if w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-l, -t), ch, font=font, fill=255, anchor="ls")
            px4 = [v >> 4 for v in im.tobytes()]
            if len(px4) % 2:
                px4.append(0)
            off = len(blob)
            blob += bytes((px4[i] << 4) | px4[i + 1] for i in range(0, len(px4), 2))
        else:
            off = len(blob)
        glyphs.append([ord(ch), round(adv * 16), l, t, w, h, off])
    return {"ascent": ascent, "descent": descent, "glyphs": glyphs}, bytes(blob)


def main() -> None:
    tmp = os.path.join(tempfile.gettempdir(), "due-crew-fonts")
    os.makedirs(tmp, exist_ok=True)
    paths = {k: fetch(u, tmp) for k, u in INTER.items()}
    faces, blobs, base = {}, [], 0
    for name, (weight, px) in FACES.items():
        meta, blob = face(paths[weight], px)
        for g in meta["glyphs"]:
            g[6] += base
        base += len(blob)
        blobs.append(blob)
        faces[name] = meta
    atlas = base64.b64encode(zlib.compress(b"".join(blobs), 9)).decode()
    logo = Image.open(LOGO).convert("RGBA")
    logo = logo.resize((round(logo.width * LOGO_H / logo.height), LOGO_H), Image.LANCZOS)
    logo64 = base64.b64encode(zlib.compress(logo.tobytes(), 9)).decode()
    with open(OUT, "w") as f:
        f.write("// Generated by tools/og_assets.py: don't edit. The glyphs are Inter\n"
                "// (SIL Open Font License 1.1, https://rsms.me/inter), drawn as 4-bit\n"
                "// alpha; the logo is docs/logo's one-line mark, as drawn.\n"
                "// Glyph: [codepoint, advance*16, left, top, width, height, offset].\n\n")
        f.write(f"export const FACES = {json.dumps(faces, separators=(',', ':'))} as const;\n\n")
        f.write(f"export const ATLAS = \"{atlas}\";\n\n")
        f.write(f"export const LOGO = {{ w: {logo.width}, h: {logo.height}, rgba: \"{logo64}\" }};\n")
    print(f"{OUT}: {os.path.getsize(OUT) // 1024} KB, {sum(len(v['glyphs']) for v in faces.values())} glyphs, logo {logo.width}x{logo.height}")


if __name__ == "__main__":
    sys.exit(main())
